AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Describe your beanstalk application environment

Parameters:
  Environment:
    Description: Name of beanstalk environment
    Type: String
    Default: Development
  ApplicationStackName:
    Description: Stack name of the beanstalk application
    Type: String
    Default: beanstalk-app
  CNAMEPrefix:
    Description: CNAME in the environment URL
    Type: String
    Default: development-highr
  SolutionStackName:
    Description: Environment solution stackname
    Type: String
    Default: "64bit Amazon Linux 2018.03 v2.13.0 running Docker 18.06.1-ce"
  NetworkStackName:
    Description: Network stack name reference
    Type: String
    Default: network-test

Resources:
  BeanstalkEnvironment:
    Type: AWS::ElasticBeanstalk::Environment
    Properties:
      ApplicationName:
        Fn::ImportValue:
          !Sub ${ApplicationStackName}
      EnvironmentName: !Ref Environment
      CNAMEPrefix: !Ref CNAMEPrefix
      SolutionStackName: !Ref SolutionStackName
      OptionSettings:
        - Namespace: 'aws:autoscaling:launchconfiguration'
          OptionName: IamInstanceProfile
          Value: !Ref InstanceProfile
        - Namespace: 'aws:elasticbeanstalk:environment'
          OptionName: ServiceRole
          Value: !Ref ServiceRole
        - Namespace: aws:ec2:vpc
          OptionName: VPCId
          Value: 
            Fn::ImportValue:
              !Sub ${NetworkStackName}-vpc
        - Namespace: aws:ec2:vpc
          OptionName: Subnets
          Value: 
            !Join
              - ','
              - 
                - Fn::ImportValue:
                    !Sub ${NetworkStackName}-pubsubA
                - Fn::ImportValue:
                    !Sub ${NetworkStackName}-pubsubB
                - Fn::ImportValue:
                    !Sub ${NetworkStackName}-pubsubC
        - Namespace: aws:ec2:vpc
          OptionName: ELBSubnets
          Value: 
            !Join
              - ','
              - 
                - Fn::ImportValue:
                    !Sub ${NetworkStackName}-pubsubA
                - Fn::ImportValue:
                    !Sub ${NetworkStackName}-pubsubB
                - Fn::ImportValue:
                    !Sub ${NetworkStackName}-pubsubC
      Tags:
        -
          Key: environment
          Value: !Ref Environment

  ServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: ''
            Effect: Allow
            Principal:
              Service: "elasticbeanstalk.amazonaws.com"
            Action: 'sts:AssumeRole'
            Condition:
              StringEquals:
                'sts:ExternalId': elasticbeanstalk
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 'elasticloadbalancing:DescribeInstanceHealth'
                  - 'ec2:DescribeInstances'
                  - 'ec2:DescribeInstanceStatus'
                  - 'ec2:GetConsoleOutput'
                  - 'ec2:AssociateAddress'
                  - 'ec2:DescribeAddresses'
                  - 'ec2:DescribeSecurityGroups'
                  - 'sqs:GetQueueAttributes'
                  - 'sqs:GetQueueUrl'
                  - 'autoscaling:DescribeAutoScalingGroups'
                  - 'autoscaling:DescribeAutoScalingInstances'
                  - 'autoscaling:DescribeScalingActivities'
                  - 'autoscaling:DescribeNotificationConfigurations'
                Resource:
                  - '*'
      Path: /
  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles:
        - !Ref InstanceProfileRole
  InstanceProfileRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - "ec2.amazonaws.com"
            Action:
              - 'sts:AssumeRole'
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Sid: ECSAccess
                Effect: Allow
                Action:
                  - 'ecs:StartTask'
                  - 'ecs:StopTask'
                  - 'ecs:RegisterContainerInstance'
                  - 'ecs:DeregisterContainerInstance'
                  - 'ecs:DescribeContainerInstances'
                  - 'ecs:DiscoverPollEndpoint'
                  - 'ecs:Submit*'
                  - 'ecs:Poll'
                Resource: '*'
              - Sid: QueueAccess
                Action:
                  - 'sqs:ChangeMessageVisibility'
                  - 'sqs:DeleteMessage'
                  - 'sqs:ReceiveMessage'
                  - 'sqs:SendMessage'
                Effect: Allow
                Resource: '*'
              - Sid: MetricsAccess
                Action:
                  - 'cloudwatch:PutMetricData'
                Effect: Allow
                Resource: '*'
      Path: /