AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Describe the RDS instance and its properties

Parameters:
  NetworkStackName:
    Description: Network stack name reference
    Type: String
    Default: network-test
  VPCCidr:
    Description: VPC Cidr block reference
    Type: String
    Default: 10.1.0.0/16

Resources:
  EC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow mysql connection inside vpc
      VpcId: 
        Fn::ImportValue:
          !Sub ${NetworkStackName}-vpc
      SecurityGroupIngress:
        - 
          IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          CidrIp: !Ref VPCCidr
      SecurityGroupEgress:
        - 
          IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          CidrIp: !Ref VPCCidr

  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: DB Subnet group
      SubnetIds:
        - Fn::ImportValue:
            !Sub ${NetworkStackName}-privsubA
        - Fn::ImportValue:
            !Sub ${NetworkStackName}-privsubB
        - Fn::ImportValue:
            !Sub ${NetworkStackName}-privsubC      

  RDSInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: 20
      AllowMajorVersionUpgrade: true
      BackupRetentionPeriod: 7
      DBInstanceClass: db.t2.micro
      DBInstanceIdentifier: !Sub ${AWS::StackName}
      Engine: mariadb
      EngineVersion: 10.3
      MultiAZ: false
      PubliclyAccessible: false
      MasterUsername: root
      MasterUserPassword: thequickbrownfox
      DBSecurityGroups:
        - !Ref DbSecurityByEC2SecurityGroup
      DBSubnetGroupName: !Ref DBSubnetGroup
      