AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Describe the RDS instance and its properties

Parameters:
  NetworkStackName:
    Description: Network stack name reference
    Type: String
    Default: network-test
  VPCCidr:
    Description: VPC Cidr block reference
    Type: String
    Default: 10.1.0.0/16

Resources:
  DbSecurityByEC2SecurityGroup:
    Type: AWS::RDS::DBSecurityGroup
    Properties:
      GroupDescription: Description for the DB security group
      DBSecurityGroupIngress:
        - 
          CIDRIP: !Ref VPCCidr
      EC2VpcId: 
        Fn::ImportValue:
          !Sub ${NetworkStackName}-vpc
      Tags:
        - 
          Key: Name
          Value: !Sub ${AWS::StackName}-db-sg

  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: DB Subnet group
      SubnetIds:
        - Fn::ImportValue:
            !Sub ${NetworkStackName}-privsubA
        - Fn::ImportValue:
            !Sub ${NetworkStackName}-privsubB
        - Fn::ImportValue:
            !Sub ${NetworkStackName}-privsubC      

  RDSInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: 20
      AllowMajorVersionUpgrade: true
      BackupRetentionPeriod: 7
      DBInstanceClass: db.t2.micro
      DBInstanceIdentifier: !Sub ${AWS::StackName}
      Engine: mariadb
      EngineVersion: 10.3
      MultiAZ: false
      PubliclyAccessible: false
      MasterUsername: root
      MasterUserPassword: thequickbrownfox
      DBSecurityGroups:
        - !Ref DbSecurityByEC2SecurityGroup
      DBSubnetGroupName: !Ref DBSubnetGroup
      
Outputs:
  EndpointAddress:
    Description: Database instance endpoint address
    Value: !GetAtt RDSInstance.Endpoint.Address
    Export:
      Name: !Sub ${AWS::StackName}-rds-address
  EndpointPort:
    Description: Database instance endpoint port
    Value: !GetAtt RDSInstance.Endpoint.Port
    Export:
      Name: !Sub ${AWS::StackName}-rds-port